### ISSUE TITLE
Phasing away from Backend Services as data storage provider

### ISSUE THREAD

**Issue by etabakov** [tralves/groceries-ns-vue#12]
As Backend Services is going [to be discontinued](https://docs.telerik.com/platform/help/discontinuation), the template should be migrated to some other data storage. The [getting started tutorial of {N}](https://docs.nativescript.org/tutorial/chapter-4#chapter-4nativescript-modules) is already migrated to [Kinvey](https://www.kinvey.com/). Probably we should do the same with this app.

I will be happy to work on this, unless there is already something in motion on this topic.

**Comment by tralves** [comment]
Hi!

Only now I found time to update this app. I started using the new API in this branch:
https://github.com/tralves/groceries-ns-vue/tree/vue-cli-template

I copied the parameters, urls, etc from the {N} version of the app, but I still can’t login for some reason. The pertinent files are:
https://github.com/tralves/groceries-ns-vue/blob/vue-cli-template/src/services/BackendService.js
https://github.com/tralves/groceries-ns-vue/blob/vue-cli-template/src/services/LoginService.js

The register call returns a 201 with the content:
{"Username":"tralves@gmail.com","Email":"tralves@gmail.com","Password":"12345","password":"befb09ea-d9c8-46dd-9faf-192d814b2aad","username":"b65ffb77-9437-4918-bce1-082789e6d2ff","_kmd":{"lmt":"2018-05-08T12:22:09.857Z","ect":"2018-05-08T12:22:09.857Z","authtoken":"ea134ca3-85b0-4cf4-996e-d0922daa8150.8IyoGlu2VXVEiaQlo+B83d20QV3D2gkdsIzC6X9TC0c="},"_id":"5af196715997e42d79b5a0bc","_acl":{"creator":"5af196715997e42d79b5a0bc”}

But then the login always returns a 401. I will look into it later, but meanwhile if you could make sure the API is working and take a look at the code to see if there is something obvious I am missing, I would be very thankful!

Thanks!
Tiago

**Comment by tralves** [comment]
Nvm! Figured it out. The register parameters were not cased properly.

Thanks!
