### ISSUE TITLE
Webpack watcher creates an endless loop

### ISSUE THREAD

**Issue by tjvantoll** [tralves/groceries-ns-vue#13]
Hey @tralves,

Awesome work on this sample! Finally got some time to look through it today and it’s amazing to see this working with Vue.

I had no issues getting the app up and running with your instructions, but I did have a problem during development. Specifically, every time I make a change I get stuck in a loop where the webpack watcher detects a change, and triggers an update of the app.... but that update keeps happening over and over again. Basically I’m stuck in an endless loop of installs.

Any idea what might be going on here? I’m using `tns run android` if it matters, and I’m happy to provide any more detail that might help you figure out what’s up.

Again thanks for your work on this sample. Hopefully this is just something silly I’m doing.

**Comment by tjvantoll** [comment]
I confirmed that I hit the same loop when working on iOS. The change I make does get applied appropriately, I just get stuck in a loop.

**Comment by jiraiya972** [comment]
try to ignore the tns folder in your **_webpack.config.js_**

I add ignore pluging

`
//ingore tns directory to avoid build loop

new webpack.WatchIgnorePlugin([join(__dirname, 'tns')])
`

Work for me.
