### ISSUE TITLE
SyntaxError: Unexpected token '<' in Groceries.vue

### ISSUE THREAD

**Issue by stromi** [tralves/groceries-ns-vue#14]
Hi there @tralves , 

first, I really appreciate all the work you've done with NS & Vue :) 

But actually there is a small problem when trying to run this (followed your readme of course):

`file:///app/components/Groceries/Groceries.vue:1: JS ERROR SyntaxError: Unexpected token '<'`

Do you have any ideas, tips, whatever(s) for this? Some config modifications or anything else? :) 

Thanks in advance!

**Comment by tralves** [comment]
run the tns command inside the `tns` folder.
