### ISSUE TITLE
Template Webpack

### ISSUE THREAD

**Issue by brunokunace** [tralves/groceries-ns-vue#15]
Hi @tralves , you have a template (like vue-cli make) with webpack (i see the use this on grocery, but i need a clean/simple boilerplate to initial dev)

thanks!

**Comment by tralves** [comment]
The template used in the Groceries app was this one https://github.com/tralves/nativescript-vue-webpack-template.

But the best way to start right now is using this template: https://github.com/nativescript-vue/vue-cli-template
