### ISSUE TITLE
Cannot find module Login

### ISSUE THREAD

**Issue by MarioAda** [tralves/groceries-ns-vue#21]
I just downloaded it and ran `npm install` then `npm run watch:android` and it crashed

**Comment by tralves** [comment]
Hi! You'll have to be more specific than that. I just tried compiling and installing from a new cloned project and it worked. Can you post the error with some context?

**Comment by MarioAda** [comment]
Alright man, here you go:
![weird](https://user-images.githubusercontent.com/34167299/41206486-5c9d6e9c-6d0d-11e8-96b5-7e49e4cc11c8.png)

**Comment by tralves** [comment]
Sorry, I missed your reply. Anyway, I just updated the project to use ns-vue 2. Should be working now.
