### ISSUE TITLE
Debug Problem

### ISSUE THREAD

**Issue by kylawamg** [tralves/groceries-ns-vue#22]
Hi guys,

Thanks for all your work, is awesome! One question, when I launch npm run debug:ios I get a url for Chrome, thats ok, but if I inspect the Source tab I cannot find any .vue file there, just the JS compressed and thats very difficult to debug...I think Im missing something but I dont know what, can u help me please?

Thanks!!

**Comment by tralves** [comment]
Yeah, you can't debug .vue files yet. Just the raw JS. However, that was good enough for me to do some basic debugging. Sooner or later someone will figure out how to debug .vue files in NS-Vue.
