### ISSUE TITLE
Cannot Debug and Watch

### ISSUE THREAD

**Issue by auhgnep** [tralves/groceries-ns-vue#23]
Hi!
I want your help!
I can't debug and watch, just build success.
--------------------------------------------
npm run debug:android
Preparing project...
Project successfully prepared (Android)
Installing...
Successfully installed on device with identifier 'emulator-5554'.
Successfully transferred all files.
Unable to apply changes on device: emulator-5554. Error is: The application org.nativescript.groceriesvue is not installed on device with identifier emulator-5554..
-------------------------------------------------
npm run watch:android
System.err: android.content.pm.PackageManager$NameNotFoundException: org.nativescript.groceriesvue
System.err: 	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:378)
System.err: 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:360)

**Comment by tralves** [comment]
Hi, I'm sorry, I don't know how to solve that. That error started showing up for some reason and I couldn't figure out why...

**Comment by oliversommer** [comment]
to me it looks as if there is a wrong appId written in template/app/App_Resources/Android/app.gradle:
"org.nativescript.groceries" is being declared but it should be "org.nativescript.groceriesvue".
so it installs the former one and later on cannot find the latter.
