### ISSUE TITLE
Unexpected Token Error on First Launch Fresh Download

### ISSUE THREAD

**Issue by seivad** [tralves/groceries-ns-vue#26]
I just downloaded the repo to try out and after running an ```npm install``` and ```tns run ios --bundle``` I receive the following error:

```JavaScript error:
file:///app/bundle.js:281:8: JS ERROR SyntaxError: Unexpected token '...'. Expected a property name.```

The loading image launches but then crashes after a number of seconds. Does this work for anyone else?

**Comment by tralves** [comment]
@seivad The project was not updated correctly. I just pushed an update to use ns-vue 2.

Please update your project, `rm -rf platforms` and try again.
