### ISSUE TITLE
Can't run on android / ios

### ISSUE THREAD

**Issue by dantanie** [tralves/groceries-ns-vue#28]
Hi, thanks for this project but sadly I can't run it after installation>

npm install
tns build android
tns run android --bundle 

crashed at first time try same as I tried for ios

Getting a lot of errors on console .

** BUILD FAILED **

Command xcodebuild failed with exit code 65
student:groceries mohammedbashiru$ tns run android --bundle
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Preparing project...
Project successfully prepared (Android)
Refreshing application on device emulator-5554...
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
System.err: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
System.err: 	at com.tns.Module.bootstrapApp(Module.java:311)
System.err: 	at com.tns.Runtime.run(Runtime.java:544)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
System.err: 	... 8 more
System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
System.err: 	at com.tns.Module.resolvePathHelper(Module.java:146)
System.err: 	at com.tns.Module.bootstrapApp(Module.java:309)
System.err: 	... 12 more
Successfully synced application org.nativescript.groceriesvue on device emulator-5554.

**Comment by tralves** [comment]
Try `rm -rf platforms` and then run `tns run android --bundle`. 

You should have run `tns build android` with `--bundle too` and probably that messed with the build. In any case, you don't have to run `tns build android` at all.

**Comment by dantanie** [comment]
Yes thanks it worked. I cloned again did 

> npm-install

> tns build android --bundle
