### ISSUE TITLE
Async Deps

### ISSUE THREAD

**Issue by ksnyde** [tralves/groceries-ns-vue#3]
I was noticing in the Rollup build process the following warning comes up:

![image](https://user-images.githubusercontent.com/980757/31833423-5a2c051a-b57f-11e7-9f9d-f2e7b7c36fb9.png)

This can be traced back to this description in Rollup:

> https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency

which I presume means that while our own code is being aggregated and shaken the external _deps_ are not. I think this is likely NOT desired but not entirely sure.

**Comment by tralves** [comment]
Yup. The warnings go away when the libs are added to the `external(id) {` part in the rollup config, but    clearly there must be something wrong...

**Comment by ksnyde** [comment]
I tried adding this:

    external: [
      './node_modules/email-validator/index.js',
      './node_modules/nativescript-theme-core/css/*.css',
      './node_modules/nativescript-theme-core/scss/**/*.scss',
      './node_modules/nativescript-vue/dist/index.js',
      './node_modules/tns-core-modules/bundle-entry-points.js',
      './node_modules/vue-router/dist/vue-router.js',
      './node_modules/vuex/dist/vuex.js',
      './node_modules/vuex/dist/logger.js',
      './node_modules/vuex-router-sync/index.js',
    ],

but still get the same error. Have you got it working?

**Comment by ksnyde** [comment]
Interesting. I bump `rollup-plugin-vue` to `2.5.2` (from `2.4.2`) and the error is gone now.

**Comment by tralves** [comment]
Sorry, I missed your reply. Anyway, I just updated the project to use ns-vue 2. Should be working now.
