### ISSUE TITLE
Rollup config failing

### ISSUE THREAD

**Issue by ksnyde** [tralves/groceries-ns-vue#4]
when I run **npm run build** rollup is executed (`rollup -c`) and the resultant `tns/app/app.js` file is produced with no visible problems. I specifically looked in detail for any invalid references to '<template' and yet when it is run on IOS I get the following error:

> file:///app/components/Groceries/Groceries.vue:1: JS ERROR SyntaxError: Unexpected token '<'
> Oct 22 18:36:19 Zippy com.apple.CoreSimulator.SimDevice.E11F3013-FD84-46E7-A1C7-EF6549BA9355[8869] (UIKitApplication:org.nativescript.groceriesvue[0x6ca1][8890][99648]): Service exited due to Segmentation fault: 11

It feels like this must be an issue due to the single-file components not being processed by Rollup or Vue-Rollup. I'm shooting in the dark here a little but would really like to get some insight into this.

**Comment by ksnyde** [comment]
BTW, I'm assuming the error is in someway trying to treat the full `.vue` file as a JS file rather than only the `<script> ... </script>` portion of the file.

**Comment by tralves** [comment]
Closing because the rollup build is no longer being used.
