### ISSUE TITLE
Backend, por favor?

### ISSUE THREAD

**Issue by irthos** [tralves/groceries-ns-vue#6]
Hi, great work translating into Vue here! Would it be possible to share the backend, as well?

**Comment by tralves** [comment]
Hi!

This app uses the same backend as the [original Groceries app](https://github.com/NativeScript/sample-Groceries). The backend is a service provided by Telerik backend services (see [here](http://docs.telerik.com/platform/backend-services/rest/what-are-telerik-backend-services)). I don't have the code for that.

**Comment by irthos** [comment]
Gotcha, thanks!
